module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require("nativewind/preset")], // <--- Add this line!
  theme: {
    extend: {
      fontSize: {
        '3xs': '8px',
        '2xs': '10px',
        '15px': '15px',
        '17px': '17px',
      },
      colors: {
        'app-bg': 'var(--color-app-bg)',
        'surface-base': 'var(--color-surface-base)',
        'surface-elevated': 'var(--color-surface-elevated)',
        'card-base': 'var(--color-card-base)',
        'zinc-900': 'var(--color-zinc-900)',
        'emerald-bg-dark': 'var(--color-emerald-bg-dark)',
        'emerald-surface-dark': 'var(--color-emerald-surface-dark)',
        'emerald-border-dark': 'var(--color-emerald-border-dark)',
        'emerald-highlight-dark': 'var(--color-emerald-highlight-dark)',
        'emerald-highlight-darker': 'var(--color-emerald-highlight-darker)',
        'red-bg-dark': 'var(--color-red-bg-dark)',
        'red-surface-dark': 'var(--color-red-surface-dark)',
        'indigo-bg-dark': 'var(--color-indigo-bg-dark)',
        'brand-primary': 'var(--color-brand-primary)',
        'brand-violet': 'var(--color-brand-violet)',
        'brand-purple': 'var(--color-brand-purple)',
        'brand-indigo': 'var(--color-brand-indigo)',
        'brand-deep': 'var(--color-brand-deep)',
        'emerald-500': 'var(--color-emerald-500)',
        'green-500': 'var(--color-green-500)',
        'red-500': 'var(--color-red-500)',
        'amber-500': 'var(--color-amber-500)',
        'yellow-500': 'var(--color-yellow-500)',
        'yellow-400': 'var(--color-yellow-400)',
        'orange-500': 'var(--color-orange-500)',
        'orange-600': 'var(--color-orange-600)',
        'blue-500': 'var(--color-blue-500)',
        'zinc-800': 'var(--color-zinc-800)',
        'neutral-800': 'var(--color-neutral-800)',
        'zinc-700': 'var(--color-zinc-700)',
        'zinc-500': 'var(--color-zinc-500)',
        'zinc-300': 'var(--color-zinc-300)',
        'violet-50': 'var(--color-violet-50)',
        'violet-200': 'var(--color-violet-200)',
        'red-50': 'var(--color-red-50)',
        'red-200': 'var(--color-red-200)',

        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        bordercolor: 'var(--color-border)',
        primary: 'var(--color-text-primary)',
        secondary: 'var(--color-text-secondary)',
        tertiary: 'var(--color-text-tertiary)',
        'brand-primary': 'var(--color-brand-primary)',
        'brand-primary-content': 'var(--color-brand-primary-content)',
        'status-danger': 'var(--color-status-danger)',
        'status-success': 'var(--color-status-success)',
      }
    },
  },
  plugins: [],
}
